services:
  postgres:
    image: postgres:16-alpine
    container_name: interacthub-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: .
    container_name: interacthub-api
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};SSL Mode=${DB_SSL_MODE};Trust Server Certificate=true
      - JwtSettings__SecretKey=${JwtSettings__SecretKey}
      - JwtSettings__Issuer=${JwtSettings__Issuer}
      - JwtSettings__Audience=${JwtSettings__Audience}
      - JwtSettings__ExpirationInMinutes=${JwtSettings__ExpirationInMinutes}
      - AllowedOrigins=${AllowedOrigins}
    restart: unless-stopped
      

volumes:
  postgres_data:
